# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/d2tmo/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/samsung/d2tmo/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/samsung/d2tmo/proprietary/lib/libril.so:obj/lib/libril.so \
	vendor/samsung/d2tmo/proprietary/lib/libv8.so:obj/lib/libv8.so

PRODUCT_COPY_FILES += \
  vendor/samsung/d2tmo/proprietary/etc/gps.conf:system/etc/gps.conf \
  vendor/samsung/d2tmo/proprietary/bin/immvibed:system/bin/immvibed \
  vendor/samsung/d2tmo/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
  vendor/samsung/d2tmo/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
  vendor/samsung/d2tmo/proprietary/bin/btnvtool:system/bin/btnvtool \
  vendor/samsung/d2tmo/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/samsung/d2tmo/proprietary/bin/port-bridge:system/bin/port-bridge \
  vendor/samsung/d2tmo/proprietary/bin/thermald:system/bin/thermald \
  vendor/samsung/d2tmo/proprietary/bin/usbhub:system/bin/usbhub \
  vendor/samsung/d2tmo/proprietary/bin/usbhub_init:system/bin/usbhub_init \
  vendor/samsung/d2tmo/proprietary/bin/time_daemon:system/bin/time_daemon \
  vendor/samsung/d2tmo/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
  vendor/samsung/d2tmo/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
  vendor/samsung/d2tmo/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
  vendor/samsung/d2tmo/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
  vendor/samsung/d2tmo/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
  vendor/samsung/d2tmo/proprietary/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
  vendor/samsung/d2tmo/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
  vendor/samsung/d2tmo/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
  vendor/samsung/d2tmo/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
  vendor/samsung/d2tmo/proprietary/etc/wifi/bcmdhd_apsta.bin_b1:system/etc/wifi/bcmdhd_apsta.bin_b1 \
  vendor/samsung/d2tmo/proprietary/etc/wifi/bcmdhd_apsta.bin_b2:system/etc/wifi/bcmdhd_apsta.bin_b2 \
  vendor/samsung/d2tmo/proprietary/etc/wifi/bcmdhd_mfg.bin_b1:system/etc/wifi/bcmdhd_mfg.bin_b1 \
  vendor/samsung/d2tmo/proprietary/etc/wifi/bcmdhd_mfg.bin_b2:system/etc/wifi/bcmdhd_mfg.bin_b2 \
  vendor/samsung/d2tmo/proprietary/etc/wifi/bcmdhd_p2p.bin_b1:system/etc/wifi/bcmdhd_p2p.bin_b1 \
  vendor/samsung/d2tmo/proprietary/etc/wifi/bcmdhd_p2p.bin_b2:system/etc/wifi/bcmdhd_p2p.bin_b2 \
  vendor/samsung/d2tmo/proprietary/etc/wifi/bcmdhd_sta.bin_b1:system/etc/wifi/bcmdhd_sta.bin_b1 \
  vendor/samsung/d2tmo/proprietary/etc/wifi/bcmdhd_sta.bin_b2:system/etc/wifi/bcmdhd_sta.bin_b2 \
  vendor/samsung/d2tmo/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
  vendor/samsung/d2tmo/proprietary/etc/wifi/nvram_mfg.txt_murata:system/etc/wifi/nvram_mfg.txt_murata \
  vendor/samsung/d2tmo/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
  vendor/samsung/d2tmo/proprietary/etc/wifi/nvram_net.txt_murata:system/etc/wifi/nvram_net.txt_murata \
  vendor/samsung/d2tmo/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
  vendor/samsung/d2tmo/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/samsung/d2tmo/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/samsung/d2tmo/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
  vendor/samsung/d2tmo/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
  vendor/samsung/d2tmo/proprietary/lib/libaudio_processing.so:system/lib/libaudio_processing.so \
  vendor/samsung/d2tmo/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
  vendor/samsung/d2tmo/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
  vendor/samsung/d2tmo/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
  vendor/samsung/d2tmo/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
  vendor/samsung/d2tmo/proprietary/lib/libchromatix_s5k6a3yx_default_video.so:system/lib/libchromatix_s5k6a3yx_default_video.so \
  vendor/samsung/d2tmo/proprietary/lib/libchromatix_s5k6a3yx_preview.so:system/lib/libchromatix_s5k6a3yx_preview.so \
  vendor/samsung/d2tmo/proprietary/lib/libchromatix_s5k6a3yx_vt.so:system/lib/libchromatix_s5k6a3yx_vt.so \
  vendor/samsung/d2tmo/proprietary/lib/libchromatix_s5k6a3yx_vt_hd.so:system/lib/libchromatix_s5k6a3yx_vt_hd.so \
  vendor/samsung/d2tmo/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
  vendor/samsung/d2tmo/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
  vendor/samsung/d2tmo/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
  vendor/samsung/d2tmo/proprietary/lib/libDxHdcp.so:system/lib/libDxHdcp.so \
  vendor/samsung/d2tmo/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/samsung/d2tmo/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
  vendor/samsung/d2tmo/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
  vendor/samsung/d2tmo/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
  vendor/samsung/d2tmo/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/samsung/d2tmo/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/samsung/d2tmo/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
  vendor/samsung/d2tmo/proprietary/lib/libseccamera_jni.so:system/lib/libseccamera_jni.so \
  vendor/samsung/d2tmo/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/samsung/d2tmo/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/samsung/d2tmo/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/samsung/d2tmo/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/samsung/d2tmo/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
  vendor/samsung/d2tmo/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
  vendor/samsung/d2tmo/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/samsung/d2tmo/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/samsung/d2tmo/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
  vendor/samsung/d2tmo/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
  vendor/samsung/d2tmo/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
  vendor/samsung/d2tmo/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
  vendor/samsung/d2tmo/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
  vendor/samsung/d2tmo/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
  vendor/samsung/d2tmo/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/samsung/d2tmo/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/samsung/d2tmo/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/samsung/d2tmo/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/samsung/d2tmo/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
  vendor/samsung/d2tmo/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/samsung/d2tmo/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/samsung/d2tmo/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/samsung/d2tmo/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/samsung/d2tmo/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/samsung/d2tmo/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/samsung/d2tmo/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/samsung/d2tmo/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
  vendor/samsung/d2tmo/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
  vendor/samsung/d2tmo/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
  vendor/samsung/d2tmo/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
  vendor/samsung/d2tmo/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/samsung/d2tmo/proprietary/bin/netmgrd:system/bin/netmgrd \
  vendor/samsung/d2tmo/proprietary/bin/sec-ril:system/bin/sec-ril \
  vendor/samsung/d2tmo/proprietary/bin/qmiproxy:system/bin/qmiproxy \
  vendor/samsung/d2tmo/proprietary/bin/qmuxd:system/bin/qmuxd \
  vendor/samsung/d2tmo/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/samsung/d2tmo/proprietary/bin/rild:system/bin/rild \
  vendor/samsung/d2tmo/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
  vendor/samsung/d2tmo/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/samsung/d2tmo/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/samsung/d2tmo/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/samsung/d2tmo/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/samsung/d2tmo/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/samsung/d2tmo/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
  vendor/samsung/d2tmo/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
  vendor/samsung/d2tmo/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
  vendor/samsung/d2tmo/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/samsung/d2tmo/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
  vendor/samsung/d2tmo/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
  vendor/samsung/d2tmo/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/samsung/d2tmo/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/samsung/d2tmo/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/samsung/d2tmo/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/samsung/d2tmo/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
  vendor/samsung/d2tmo/proprietary/lib/libv8.so:system/lib/libv8.so
